// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "Alert",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "Alert",
            targets: ["Alert"],
            bundleIdentifier: "yossibank-yahoo.co.jp.Alert",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SnapKit/SnapKit", "5.7.1" ..< "6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "Alert",
            dependencies: [
                .product(name: "SnapKit", package: "snapkit"),
                .product(name: "SnapKit-Dynamic", package: "snapkit")
            ],
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
