// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "TheComposableArchitecture",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TheComposableArchitecture",
            targets: ["TheComposableArchitecture"],
            bundleIdentifier: "yossibank-yahoo.co.jp.TheComposableArchitecture",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coins),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture",
            "1.5.0" ..< "2.0.0"
        )
    ],
    targets: [
        .executableTarget(
            name: "TheComposableArchitecture",
            dependencies: [
                .product(
                    name: "ComposableArchitecture",
                    package: "swift-composable-architecture"
                )
            ],
            path: "Sources"
        )
    ]
)
