// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sample",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Sample",
            targets: ["Sample"],
            bundleIdentifier: "yossibank-yahoo.co.jp.Sample",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "Package", path: "../../Package")
    ],
    targets: [
        .executableTarget(
            name: "Sample",
            dependencies: [
                .product(name: "API", package: "Package", condition: nil)
            ],
            path: "Sources"
        )
    ]
)
