///
/// @Generated by Mockolo
///

#if DEBUG

    @testable import API
    import CodingKeys
    import StructBuilder

    final class TestProtocolMock: TestProtocol {
        init() {}

        private(set) var hogeCallCount = 0
        var hogeHandler: (() -> (String))?
        func hoge() -> String {
            hogeCallCount += 1
            if let hogeHandler {
                return hogeHandler()
            }
            return ""
        }
    }

#endif
