// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "CleanArchitecture",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "CleanArchitecture",
            targets: ["CleanArchitecture"],
            bundleIdentifier: "yossibank-yahoo.co.jp.CleanArchitecture",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [],
    targets: [
        .executableTarget(
            name: "CleanArchitecture",
            path: "Sources"
        )
    ]
)
